ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS legal_name VARCHAR(150);
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS country_of_residence VARCHAR(100);
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS identity_document_type VARCHAR(50);
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS identity_document_url TEXT;
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS portrait_url TEXT;
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS phone_number VARCHAR(30);
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS current_title VARCHAR(150);
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS current_company VARCHAR(150);
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS primary_domain VARCHAR(120);
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS linkedin_url TEXT;
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS github_url TEXT;
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS portfolio_evidence_url TEXT;
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS certificate_url TEXT;
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS bank_account_name VARCHAR(150);
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS bank_name VARCHAR(150);
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS bank_account_number VARCHAR(80);
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS bank_branch VARCHAR(150);
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS tax_id VARCHAR(80);
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS mentor_agreement_accepted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS dispute_policy_accepted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE mentor_profiles ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ;
